theme: jekyll-theme-cayman
title: RF Respiration Monitoring
show_excerpts: false # set to true to show excerpts on the homepage

project:
    name: RF Respiration Monitoring

plugins:
 - jekyll-feed
 - jekyll-seo-tag
